language: go

go:
  - 1.6

sudo: false
cache: bundler

before_install:
  - pip install --user codecov
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:

script:
  - go test ./...
  - go test -benchmem -bench .
  - /bin/sh ./go-coverall.sh

